"""Criação inicial do banco de dados

Revision ID: 22ae2e02d384
Revises: 
Create Date: 2025-01-26 19:56:47.988417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22ae2e02d384'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedor',
    sa.Column('id_fornecedor', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_fornecedor', sa.String(length=100), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=False),
    sa.Column('endereco', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id_fornecedor'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('loja',
    sa.Column('id_loja', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_loja', sa.String(length=100), nullable=False),
    sa.Column('endereco', sa.String(length=200), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id_loja')
    )
    op.create_table('produto',
    sa.Column('id_produto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_produto', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estoque_minimo', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_produto')
    )
    op.create_table('compra',
    sa.Column('id_compra', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_fornecedor', sa.Integer(), nullable=False),
    sa.Column('data_compra', sa.Date(), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_fornecedor'], ['fornecedor.id_fornecedor'], ),
    sa.PrimaryKeyConstraint('id_compra')
    )
    op.create_table('estoque',
    sa.Column('id_estoque', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_loja', sa.Integer(), nullable=False),
    sa.Column('id_produto', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_loja'], ['loja.id_loja'], ),
    sa.ForeignKeyConstraint(['id_produto'], ['produto.id_produto'], ),
    sa.PrimaryKeyConstraint('id_estoque'),
    sa.UniqueConstraint('id_loja', 'id_produto', name='uq_estoque_loja_produto')
    )
    op.create_table('venda',
    sa.Column('id_venda', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_loja', sa.Integer(), nullable=False),
    sa.Column('data_venda', sa.Date(), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_loja'], ['loja.id_loja'], ),
    sa.PrimaryKeyConstraint('id_venda')
    )
    op.create_table('item_compra',
    sa.Column('id_item_compra', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_compra', sa.Integer(), nullable=False),
    sa.Column('id_produto', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_compra'], ['compra.id_compra'], ),
    sa.ForeignKeyConstraint(['id_produto'], ['produto.id_produto'], ),
    sa.PrimaryKeyConstraint('id_item_compra')
    )
    op.create_table('item_venda',
    sa.Column('id_item_venda', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_venda', sa.Integer(), nullable=False),
    sa.Column('id_produto', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_produto'], ['produto.id_produto'], ),
    sa.ForeignKeyConstraint(['id_venda'], ['venda.id_venda'], ),
    sa.PrimaryKeyConstraint('id_item_venda')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_venda')
    op.drop_table('item_compra')
    op.drop_table('venda')
    op.drop_table('estoque')
    op.drop_table('compra')
    op.drop_table('produto')
    op.drop_table('loja')
    op.drop_table('fornecedor')
    # ### end Alembic commands ###
