"""Criação inicial do banco de dados

Revision ID: 702ccd1c589f
Revises: 18f55f49642c
Create Date: 2025-01-26 20:59:31.824936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '702ccd1c589f'
down_revision: Union[str, None] = '18f55f49642c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
