"""Testando Alteração

Revision ID: b14d75100dda
Revises: c9b742801e66
Create Date: 2025-01-26 21:01:52.116816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b14d75100dda'
down_revision: Union[str, None] = 'c9b742801e66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loja', sa.Column('nome_loja', sa.String(length=100), nullable=False))
    op.drop_column('loja', 'nome_loja_teste')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loja', sa.Column('nome_loja_teste', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('loja', 'nome_loja')
    # ### end Alembic commands ###
