"""Testando Alteração

Revision ID: c9b742801e66
Revises: 702ccd1c589f
Create Date: 2025-01-26 21:01:07.313281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9b742801e66'
down_revision: Union[str, None] = '702ccd1c589f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loja', sa.Column('nome_loja_teste', sa.String(length=100), nullable=False))
    op.drop_column('loja', 'nome_loja')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loja', sa.Column('nome_loja', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('loja', 'nome_loja_teste')
    # ### end Alembic commands ###
